"""
Grounding and Safety Validation Module

WHAT: Validates generated LLM responses against upstream `ExplanationRequest` context.

WHY: Reduces hallucination risk by verifying that:
     1. Every cited research source (PMID / DOI) exists in the retrieved RAG Evidence Package.
     2. Every track ID referenced in recommendation reasons exists in recommendation results.
     3. No prohibited clinical diagnoses or medical cure claims were introduced.
     4. Missing evidence packages are explicitly acknowledged rather than hallucinated.

VALIDATION ARCHITECTURE:
    ExplanationRequest Context
               ↓
    LLM Output Text / JSON
               ↓
    GroundingValidator
       ├── Citation Grounding (PMID / DOI Match)
       ├── Track Grounding (Track ID Match)
       ├── Safety Constraint Scanner (Prohibited Clinical Terms)
       └── Missing Evidence Compliance Check
               ↓
    Validated ExplanationResponse + Grounding Score + Warnings
"""

import re
from typing import Dict, Any, List, Optional
from .schemas import ExplanationRequest, ExplanationResponse


class GroundingValidator:
    """
    Deterministic validator verifying citation grounding, track ID consistency, safety constraints, and evidence compliance.
    """

    PROHIBITED_CLINICAL_TERMS = [
        "diagnose anxiety",
        "cures anxiety",
        "treats anxiety",
        "clinical treatment",
        "medical cure",
        "prescribes music",
        "psychiatric therapy"
    ]

    def validate(
        self,
        request: ExplanationRequest,
        response: ExplanationResponse
    ) -> ExplanationResponse:
        """
        Perform comprehensive grounding and safety validation on an ExplanationResponse.

        Args:
            request: The original input ExplanationRequest payload.
            response: The candidate ExplanationResponse generated by the LLM.

        Returns:
            Updated ExplanationResponse with is_validated, grounding_score, and validation_warnings.
        """
        warnings = []

        # 1. Extract valid PMIDs, DOIs, and Document IDs from EvidencePackage
        valid_pmids = set()
        valid_dois = set()
        valid_doc_ids = set()

        evidence_pkg = request.evidence_package or {}
        sources_data = evidence_pkg.get("sources", [])
        chunks_data = evidence_pkg.get("retrieved_chunks", [])

        for src in sources_data:
            if src.get("pmid"):
                valid_pmids.add(str(src["pmid"]).strip())
            if src.get("doi"):
                valid_dois.add(str(src["doi"]).strip().lower())
            if src.get("document_id"):
                valid_doc_ids.add(str(src["document_id"]).strip())

        for chunk in chunks_data:
            meta = chunk.get("metadata", {})
            if meta.get("pmid"):
                valid_pmids.add(str(meta["pmid"]).strip())
            if meta.get("doi"):
                valid_dois.add(str(meta["doi"]).strip().lower())
            if meta.get("document_id"):
                valid_doc_ids.add(str(meta["document_id"]).strip())

        # Check citations in response.sources
        for src in response.sources:
            pmid = str(src.get("pmid", "")).strip()
            doi = str(src.get("doi", "")).strip().lower()

            if pmid and pmid not in valid_pmids:
                warnings.append(f"Fabricated PMID citation detected: '{pmid}' is not in EvidencePackage.")
            if doi and doi not in valid_dois:
                warnings.append(f"Fabricated DOI citation detected: '{doi}' is not in EvidencePackage.")

        # Check PMIDs mentioned in text response
        full_text = " ".join([
            response.summary,
            " ".join(response.recommendation_reasons),
            " ".join(response.research_context),
            " ".join(response.limitations)
        ])

        pmid_matches = re.findall(r"PMID:\s*(\d+)", full_text, re.IGNORECASE)
        for pmid in pmid_matches:
            if pmid not in valid_pmids:
                warnings.append(f"Text mentions ungrounded PMID: '{pmid}'.")

        # 2. Extract valid Track IDs from recommendations
        valid_track_ids = set()
        for rec in request.recommendations or []:
            t_id = rec.get("track_id") or rec.get("id")
            if t_id:
                valid_track_ids.add(str(t_id).strip())

        # Check track IDs mentioned in recommendation reasons
        for reason in response.recommendation_reasons:
            trk_matches = re.findall(r"ID:\s*([A-Za-z0-9_\-]+)", reason)
            for trk_id in trk_matches:
                if trk_id not in valid_track_ids:
                    warnings.append(f"Recommendation reason references ungrounded track ID: '{trk_id}'.")

        # 3. Check for prohibited clinical/treatment terms
        lower_text = full_text.lower()
        for term in self.PROHIBITED_CLINICAL_TERMS:
            if term in lower_text:
                warnings.append(f"Prohibited non-clinical safety term detected in response: '{term}'.")

        # 4. Check for missing evidence compliance
        is_evidence_empty = (
            not sources_data and not chunks_data and
            evidence_pkg.get("retrieval_metadata", {}).get("total_chunks_retrieved", 0) == 0
        )

        if is_evidence_empty:
            # Response must acknowledge lack of evidence rather than claiming findings
            claimed_evidence = [rc for rc in response.research_context if "investigated" in rc.lower() or "pmid" in rc.lower()]
            if claimed_evidence:
                warnings.append("EvidencePackage is empty, but response claims specific research findings.")

        # 5. Compute grounding score and validation status
        dedup_warnings = list(dict.fromkeys(warnings))
        penalty = len(dedup_warnings) * 0.25
        score = max(0.0, round(1.0 - penalty, 2))
        is_valid = (len(dedup_warnings) == 0)

        response.is_validated = is_valid
        response.grounding_score = score
        response.validation_warnings = dedup_warnings

        return response
